version: '3'

services:

    mongo:
        image:          mongo:3.7.3
        container_name: mongo
        restart:        always
        ports:          
                        - 27017:27017
        volumes:
                        - ./data/mongo:/data/db
        networks:
                        - net-nodeclub-server

    redis:
        image:          redis:4.0.10-alpine
        container_name: redis
        restart:        always
        ports:          
                        - 6379:6379
        volumes:
                        - ./data/redis:/data
        networks:
                        - net-nodeclub-server

    nodeclub:
        image:          nodeclub
        container_name: nodeclub
        ports:
                        - 3000:3000
        volumes:
                        - ./conf/nodeclub-config.js:/nodeclub/config.js
                        - ./data/file:/nodeclub/public/upload
                        - ./log/nodeclub:/nodeclub/log
                        # - ./views/layout.html:/nodeclub/views/layout.html
                        # - ./views/sidebar.html:/nodeclub/views/sidebar.html
        networks:
                        - net-nodeclub-server

networks:
    net-nodeclub-server: